import { jsPDF } from "jspdf";

// Primary brand color #1E3A8A → RGB(30, 58, 138)
const BRAND_R = 30;
const BRAND_G = 58;
const BRAND_B = 138;

const fmt = (date) =>
  new Date(date).toLocaleDateString("en-IN", {
    day: "2-digit",
    month: "short",
    year: "numeric",
  });

const line = (doc, y) => {
  doc.setDrawColor(220, 220, 220);
  doc.line(20, y, 190, y);
};

const sectionHeader = (doc, text, y) => {
  doc.setTextColor(BRAND_R, BRAND_G, BRAND_B);
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.text(text, 20, y);
  doc.setTextColor(60, 60, 60);
  doc.setFont("helvetica", "normal");
};

const row = (doc, label, value, y) => {
  doc.setFontSize(9);
  doc.setFont("helvetica", "normal");
  doc.setTextColor(120, 120, 120);
  doc.text(label, 20, y);
  doc.setTextColor(40, 40, 40);
  doc.text(String(value ?? "—"), 90, y);
};

const generateInvoice = ({
  transactionId,
  paymentDate,
  paymentMethod,
  amount,
  expertName,
  expertSpecialization,
  upiId,
  cardLast4,
  userName,
  userEmail,
  consultationDuration = "4 Hours",
}) => {
  const doc = new jsPDF({ unit: "mm", format: "a4" });

  // ── HEADER ───────────────────────────────────────────────
  doc.setFillColor(BRAND_R, BRAND_G, BRAND_B);
  doc.rect(0, 0, 210, 38, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(22);
  doc.setFont("helvetica", "bold");
  doc.text("LAWASSIST", 105, 16, { align: "center" });

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("CONSULTATION INVOICE", 105, 25, { align: "center" });

  doc.setFontSize(8);
  doc.setTextColor(180, 200, 240);
  doc.text("Consumer Rights Legal Help System", 105, 33, { align: "center" });

  // reset colour
  doc.setTextColor(40, 40, 40);

  let y = 50;

  // ── INVOICE INFORMATION ──────────────────────────────────
  sectionHeader(doc, "Invoice Information", y);
  y += 8;
  const invoiceNo = `INV-${transactionId ? transactionId.slice(-8).toUpperCase() : "N/A"}`;
  row(doc, "Invoice No:", invoiceNo, y);          y += 7;
  row(doc, "Transaction ID:", transactionId ?? "—", y); y += 7;
  row(doc, "Date:", fmt(paymentDate), y);         y += 10;

  line(doc, y);
  y += 8;

  // ── USER INFORMATION ─────────────────────────────────────
  sectionHeader(doc, "User Information", y);
  y += 8;
  row(doc, "Name:", userName || "LawAssist User", y);  y += 7;
  row(doc, "Email:", userEmail || "—", y);             y += 10;

  line(doc, y);
  y += 8;

  // ── EXPERT INFORMATION ───────────────────────────────────
  sectionHeader(doc, "Expert Information", y);
  y += 8;
  row(doc, "Expert:", expertName ?? "—", y);                         y += 7;
  row(doc, "Specialization:", expertSpecialization || "Legal Expert", y); y += 10;

  line(doc, y);
  y += 8;

  // ── CONSULTATION DETAILS ─────────────────────────────────
  sectionHeader(doc, "Consultation Details", y);
  y += 8;
  row(doc, "Duration:", consultationDuration, y); y += 7;
  row(doc, "Consultation Fee:", `Rs.${amount}`, y); y += 10;

  line(doc, y);
  y += 8;

  // ── PAYMENT DETAILS ──────────────────────────────────────
  sectionHeader(doc, "Payment Details", y);
  y += 8;

  const methodStr =
    paymentMethod === "UPI"
      ? `UPI${upiId ? ` (${upiId})` : ""}`
      : `Card ending ****${cardLast4 || "****"}`;

  row(doc, "Payment Method:", methodStr, y);  y += 7;
  row(doc, "Payment Status:", "Success", y);  y += 10;

  line(doc, y);
  y += 10;

  // ── TOTAL AMOUNT BOX ─────────────────────────────────────
  doc.setFillColor(240, 244, 255);
  doc.roundedRect(20, y, 170, 18, 3, 3, "F");

  doc.setTextColor(BRAND_R, BRAND_G, BRAND_B);
  doc.setFontSize(11);
  doc.setFont("helvetica", "bold");
  doc.text("Total Paid:", 30, y + 12);

  doc.setFontSize(14);
  doc.text(`Rs.${amount}`, 180, y + 12, { align: "right" });

  y += 26;
  line(doc, y);
  y += 8;

  // ── FOOTER ───────────────────────────────────────────────
  doc.setTextColor(150, 150, 150);
  doc.setFontSize(7.5);
  doc.setFont("helvetica", "normal");
  doc.text(
    "Generated by LawAssist \u2013 Consumer Rights Legal Help System",
    105,
    y,
    { align: "center" },
  );
  y += 6;
  doc.text(
    "This is a simulated invoice created for academic demonstration purposes.",
    105,
    y,
    { align: "center" },
  );

  // ── SAVE ─────────────────────────────────────────────────
  doc.save(`LawAssist_Invoice_${transactionId || "receipt"}.pdf`);
};

export default generateInvoice;
